#write a programme to input eight number from user and displya all unique number 
s=set()
a=int(input("enter the number="))
s.add(a)
a=int(input("enter the number="))
s.add(a)
a=int(input("enter the number="))
s.add(a)
a=int(input("enter the number="))
s.add(a)
a=int(input("enter the number="))
s.add(a)
a=int(input("enter the number="))
s.add(a)
print(s)