# write a programme of store seven fruits in a list by user input 
fruites = []
f1=input("enter the fruit name=")
fruites.append(f1)
f2=input("enter the fruit name=")
fruites.append(f2)
f3=input("enter the fruite")
fruites.append(f3)
f4=input("enter the fruite name")
fruites.append(f4)
f5=input("enter the fruite name ")
fruites.append(f5)
f6=input("enter the fruite name")
fruites.append(f6)
f7=input("enter the fruite name")
fruites.append(f7)
print(fruites)