#write a programme to accept marks of 6 student and display them in a sorted manner 
marks=[]
s1=int(input("enter the marks="))
marks.append(s1)
s2=int(input("enter the marks="))
marks.append(s2)
s3=int(input("enter the marks="))
marks.append(s3)
s4=int(input("enter the marks="))
marks.append(s4)
s5=int(input("enter the marks="))
marks.append(s5)
s6=int(input("enter the marks="))
marks.append(s6)
print(marks)